{
 "title": "K6 Load Test Dashboard",
 "tags": [ "k6" ],
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,10s,30s,1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "measurement": "http_req_duration",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "alias": "HTTP Request Duration"
    }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "measurement": "http_reqs",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "sum",
        "params": []
       }
      ]
     ],
     "alias": "HTTP Requests"
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "yaxes": [
    { "format": "short", "label": "VUs" }
   ],
   "targets": [
    {
     "measurement": "vus",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "max",
        "params": []
       }
      ]
     ],
     "alias": "VUs"
    }
   ]
  }
 ]
}