{
 "title": "Server Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Reqeuests success rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_requests_total{status=\"OK\"}[5m])) by (path)\r\n  /\r\n  sum(rate(http_requests_total[5m])) by (path)\r\n) * 100\r\n"
    }
   ]
  },
  {
   "title": "General mean latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Rateservice logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container_name=\"rateservice\"} | json msg=\"message\"\r\n| line_format `{{.msg}}`\r\n| unpack\r\n| json\r\n| label_format event=\"{{.event_extracted}}\"\r\n| drop msg, event_extracted"
    }
   ]
  },
  {
   "title": "Notifier logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{container_name=\"notifier\"} | json msg=\"message\"\r\n| line_format `{{.msg}}`\r\n| unpack\r\n| json\r\n| label_format event=\"{{.event_extracted}}\"\r\n| drop msg, event_extracted"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Go Memory Alloc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Go GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}