name: LintersCheck

on:
  push:
    branches:
      - project
  pull_request:
    branches:
      - '*'

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.0.1
