name: LintersCheck

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          args: --config=conf/.golangci.yml